# Generated by Django 6.0 on 2025-12-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterreading',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='cold_cost',
            field=models.FloatField(verbose_name='Стоимость холодной воды'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='cold_curr',
            field=models.FloatField(verbose_name='Холодная вода (текущее)'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='cold_prev',
            field=models.FloatField(verbose_name='Холодная вода (предыдущее)'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='electricity',
            field=models.FloatField(default=0, verbose_name='Электричество'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='hot_cost',
            field=models.FloatField(verbose_name='Стоимость горячей воды'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='hot_curr',
            field=models.FloatField(verbose_name='Горячая вода (текущее)'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='hot_prev',
            field=models.FloatField(verbose_name='Горячая вода (предыдущее)'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='internet',
            field=models.FloatField(default=0, verbose_name='Интернет'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='sewage_cost',
            field=models.FloatField(verbose_name='Стоимость водоотведения'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='total',
            field=models.FloatField(verbose_name='Итого'),
        ),
    ]
